### ISSUE TITLE
Create PostGreSQL Script

### ISSUE THREAD

**Issue by kirubeltadesse** [Swarmies/sap-core#39]
# Description 

Create a `PostgreSQL` Script for all the tables and their relationship.

## Acceptable Criteria 

- Create a `PostgreSQL` script (including all the tables and relationships)
- Create a script to populate fake data

## Related Story 

Use the table naming and relationship from this #19  

## Technical Info

There are different ways of creating the script 
using [lucid diagram](https://www.lucidchart.com/pages/examples/er-diagram-tool#video)
or 
you can use the PostgreSQL tool

**Comment by dinaolmelak** [comment]
Updated the ER_diagram documentation in the following PR #43

**Comment by dinaolmelak** [comment]
I had used Lucidchart create the following diagram based on the ER_Diagram in the documentation. I will be exporting it as a POSTGREsql schema and create the databases.

![Image](https://user-images.githubusercontent.com/32272045/174461285-dc74b3e8-dc5e-4c8b-ac9c-b283945b2e99.png)

**Comment by dinaolmelak** [comment]
I just created the database based on the above [diagram](https://github.com/Swarmies/sap-web/issues/39#issuecomment-1159590319). The script I exported from Lucid Chart worked fine. However, I had to change the `string` to `VARCHAR`, because POSTGREsql does not have string datatype.

![Image](https://user-images.githubusercontent.com/32272045/175358821-daa67886-02bf-49ce-882a-bc1ab1b81998.png)

**Comment by kirubeltadesse** [comment]
@dinaolmelak yes, the datatypes are different between language and database language. `VARCHAR` seems the right type for `string` you can refer to [here](https://www.postgresql.org/docs/current/datatype.html) for more information. 

I believe what is remaining now is creating a script to populate the tables using fake data.

**Comment by dinaolmelak** [comment]
For tracking the database table structures and fake data. 
```
/sap/resources/script.sql
/sap/resources/schema.sql
```
should it be stored like that?

**Comment by kirubeltadesse** [comment]
> 
Let me ask you this thing where is the /sap folder going to be?

**Comment by dinaolmelak** [comment]
By `/sap` I meant `./` (i.e `./resources/script.sql` and `./resources/schema.sql`)

**Comment by kirubeltadesse** [comment]
> By `/sap` I meant `./`

I guess for now you can put it inside `/sap-web/sapweb/resources/` which means you need to create the `resources` folder under the already existing `sapweb` folder.
