### ISSUE TITLE
UI: Student login page

### ISSUE THREAD

**Issue by kirubeltadesse** [Swarmies/sap-core#40]
# Description 

Create a student logging page on the UI. Please referent to the [sequence diagram](https://github.com/Swarmies/sap-web/blob/develop/Doc/Sequence_Diagram.md) and their right requests. 

## Acceptable Criteria 

- Landing page (this will have the login button and signup) 
- Create the student login page
- Make sure you use Typescript
- Accept coding standard
- Update the frontend/readme.md file
- Use the right marks for later reference 

## Related Story 

This is the first landing page and doesn't relate to previous work. 

## Technical Info

[Here](https://www.freecodecamp.org/news/how-to-code-your-react-app-with-typescript/#:~:text=React%20is%20one%20of%20the,to%20use%20React%20with%20TypeScript) is typescript for react!

**Comment by dinaolmelak** [comment]
@Getnet12 , don't forget to do a fetch, Let us know if you have questions. 👍🏽 Happy coding.

**Comment by Getnet12** [comment]
Why is this ticket closed? am I missing something here

**Comment by dinaolmelak** [comment]
It got merged with the `develop` branch of the remote repository we forked from.

**Comment by dinaolmelak** [comment]
Lol, I'm sorry I got it confused with my PR

**Comment by dinaolmelak** [comment]
@Getnet12, How is it coming along?
