### ISSUE TITLE
feat(backend): Add models to backend

### ISSUE THREAD

**Issue by Roberamelaek** [Swarmies/sap-core#76]
# Description 

Create a user, student and mentor models in backend model .
go to https://swarmies.github.io/sap-web/modules/UML_diagram.html#object-model-diagram
for details 

## Acceptable Criteria 

- must follow the sapweb documentaion

## Technical Info

make the student and mentor inherit for the user models

**Comment by kirubeltadesse** [comment]
Here is a [good resource](https://dev.to/highcenburg/django-model-inheritance-4f3p#:~:text=One%20of%20the%20powerful%20features,easy%20to%20maintain%20and%20extend.) explaining different inheritance process.
