### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by kirubeltadesse** [Swarmies/sap-core#8]
# Description 

Tracking and building the application before it merges to the main repo

## Acceptable Criteria 

- Create a `.yml` file (It has been already created [Here](https://github.com/Swarmies/sap-web/blob/develop/.github/workflows/blank.yml) 
- Pull recent changes
- Update and integrate with  CircleCI

## Technical Info

[Do you have technical or additional information that can better describe the story](https://docs.travis-ci.com/user/tutorial/)

**Comment by dinaolmelak** [comment]
The free trial plan of [Travis CI is only available for 30 days](https://docs.travis-ci.com/user/billing-overview/). 
<img width="863" alt="Screen Shot 2022-05-14 at 8 30 48 PM" src="https://user-images.githubusercontent.com/32272045/168453507-4f164a2d-81e6-4d58-8754-e12bb272ab78.png">

Hence we can use [CircleCI](https://circleci.com/pricing/) which is free to use

**Comment by kirubeltadesse** [comment]
How far are we on this ticket? Are you still on a `Blocked` Status?

**Comment by kirubeltadesse** [comment]
Here is a documentation on how to configure for Docker container once the containers are merged: 
https://stackoverflow.com/questions/31213195/running-docker-container-tests-on-circleci#32727789
