### ISSUE TITLE
[Test] Semantic 

### ISSUE THREAD

**Issue by kirubeltadesse** [Swarmies/sap-core#9]
# Description 

Make sure the probot is properly configured with the repo.

## Acceptable Criteria 

- Screenshot of a build and properly documentation

## Related Story 

Does this relate to any previous work

## Technical Info

https://github.com/apps/semantic-pull-requests

**Comment by kirubeltadesse** [comment]
Semantic check missing 
![image](https://user-images.githubusercontent.com/6774894/168668611-b25f9b07-d7f2-4897-a059-6fa86b6f2c06.png)

**Comment by kirubeltadesse** [comment]
I am not sure the .github/semantic.yml not being picked up. I am guess that it is being blocked by .github/pull_request_template.md. Can you (@Getnet12) please check it using your on repo and confirm if that is the case ?

**Comment by Getnet12** [comment]
Ok, I'll check it.

**Comment by kirubeltadesse** [comment]
Interesting, the app have to be build and deployed in order for it to work. [Here](https://probot.github.io/docs/)

**Comment by Getnet12** [comment]
That makes no sense to me. I couldn't find it in the link you provided me, btw. Anyway, we can talk about it in our meeting.

**Comment by kirubeltadesse** [comment]
Yes, don't worry about that. I will take care this one. It is a little be complicated than I expected it to be. 

1. Create an app [here](https://probot.github.io/docs/development/)
2. Configuring with GitHub credential and registry [here](https://probot.github.io/docs/configuration/)
3. Deploying to heroku [here]( https://probot.github.io/docs/deployment/#heroku)

**Comment by Getnet12** [comment]
I see It has a lot of steps. I thought I was done by doing those 2 steps😀

**Comment by kirubeltadesse** [comment]
> I see It has a lot of steps. I thought I was done by doing those 2 steps😀

That was what I thought at first too. Now, I see you can install some of the apps directory into GitHub or as a library into the app your are developing. No need to worry about this to much. I want you to focus on #13 for now.

**Comment by kirubeltadesse** [comment]
Good article about Probot: https://jasonet.co/posts/build-your-own-probot/

**Comment by kirubeltadesse** [comment]
fix with #36

**Comment by kirubeltadesse** [comment]
This is an overkill for simple impact what we want to create. I believe the desired effect is achieved using #21
